config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  root "home#index"

  get "up" => "rails/health#show", as: :rails_health_check

  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  resources :organizations, only: %i[index create show]
  resources :organization_users, only: %i[create]
  resources :projects, only: %i[create show update]
  resources :reports, only: %i[] do
    member do
      get :bundled_html, action: :bundled_html
      get "bundled_html/*path", action: :bundled_html
    end
  end


  namespace :api do
    resources :reports, only: %i[] do
      collection do
        post :simplecov
      end
    end
  end
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :organization
  has_many :reports

  validates :handle,
            presence: true,
            format: {
              with: /\A[a-z0-9\-]+\z/,
              message: "accepts only lowercase letters, numbers, and hyphens. Eg: 'my-github-repo'"
            },
            uniqueness: { scope: :organization }

  def self.find_by_token(token)
    Project.find_by(api_auth_digest: Digest::SHA512.hexdigest(token))
  end

  def reset_api_auth!
    token = "sffp1_" + SecureRandom.hex(64)
    update!(api_auth_digest: Digest::SHA512.hexdigest(token))
    token
  end

  def last_main_branch_general_coverage
    reports
      .simplecov
      .where(branch: "main")
      .where("JSON_EXTRACT(results, '$.general_coverage') IS NOT NULL")
      .order(:created_at)
      .last&.general_coverage || 0
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  helper_method :simplecov_progress, :simplecov_progress_last_year

  def create
    @project = Project.new(create_params)

    if @project.save
      flash[:success] = "Project '#{@project.handle}' created successfully!"
      redirect_to organization_path(@project.organization)
    else
      flash[:danger] = @project.errors.full_messages.to_sentence
      redirect_back(fallback_location: organizations_path)
    end
  end

  def show
    @project = projects.find(params[:id])
    @reports = @project.reports.order(created_at: :desc).limit(100)
  end

  def update
    @project = projects.find(params[:id])
    token = @project.reset_api_auth!

    flash[:success] = "Copy this token now, it will only be available once: #{token}"
    redirect_to project_path(@project)
  end

  private

  memoize def simplecov_progress
    ::Projects::SimplecovProgress.new(@project).call
  end

  memoize def simplecov_progress_last_year
    ::Projects::SimplecovProgress.new(@project, since: 365.days.ago).call
  end

  def create_params
    params
      .require(:project)
      .permit(:handle, :organization_id)
      .tap do |partial_params|
        partial_params[:handle] = partial_params[:handle]&.parameterize

        organization = current_user.organizations.find_by(id: partial_params[:organization_id])
        partial_params[:organization_id] = organization&.id
      end
  end

  def projects
    Project.where(organization: current_user.organizations)
  end
end

app/views/projects/show.html.erb
<h6><%= link_to "< #{@project.organization.handle}", organization_path(@project.organization), class: "link" %></h6>
<h5>Project</h5>
<h1><%= @project.handle %></h1>

<% if simplecov_progress_last_year.present? %>
  <h4>Last 365 Days</h4>
  <% min_value = simplecov_progress_last_year.map(&:last).min - 1 %>
  <%=
    line_chart(
      simplecov_progress_last_year,
      min: min_value
    )
  %>
<% end %>

<% if simplecov_progress.present? %>
  <h4>All Time</h4>
  <%=
    line_chart(
      simplecov_progress,
      library: { scales: { y: { type: 'logarithmic' } } }
    )
  %>
<% end %>

<div>
  <ul class="list-disc">
    <h4>Reports</h4>

    <% if @reports.blank? %>
      <li>No reports yet...</li>
    <% end %>

    <% @reports.each do |report| %>
      <li>
        <%= link_to(bundled_html_report_path(report), class: "link") do %>
          <%= report.name %>
        <% end %>
        (<%= [report.branch, report.formatted_coverage].join(" - ") %>)
      </li>
    <% end %>
  </ul>
</div>

<hr class="my-8" />

<div class="flex justify-between items-start">
  <div class="card flex flex-col">
    After running your tests on your CI, zip and CURL the SimpleCov HTML report to flaky.xyz, and it shows up here.
    <br />
    <br />
    Here is an example on how to configure it on your GitHub Actions workflow:
    <br />
    Don't forget to set up your token as a secret on your repository settings.
    <textarea>
your-existing-test-action-on-github:
  permissions:
    pull-requests: write # To post comments on PR

  # ...

  steps:
    # ... Your other test steps, including Rspec/Minitest that generates the SimpleCov HTML report.

    - name: Send SimpleCov to flaky.xyz
      id: flaky-xyz-upload
      if: always()
      run: |
        zip -r simplecov.zip coverage;
        RESPONSE=$(curl -X POST https://flaky.xyz/api/reports/simplecov \
          -F "part=@simplecov.zip" \
          -F "expected_parts=1" \
          -F "run_identifier=${{ github.run_id }}" \
          -H "Authorization: Bearer ${{ secrets.FLAKY_XYZ_TOKEN }}");
        echo "MARKDOWN=$(echo $RESPONSE | jq -r '.markdown')" >> $GITHUB_OUTPUT;

    - name: Comment PR with flaky.xyz results
      uses: thollander/actions-comment-pull-request@v3
      if: always() && github.event_name == 'pull_request'
      with:
        message: |
          ${{ steps.flaky-xyz-upload.outputs.MARKDOWN }}
        comment-tag: flaky-xyx-simplecov
        mode: recreate
    </textarea>

    <a href="https://github.com/Superfiliate/flaky/blob/main/.github/workflows/ci.yml" class="link">
      You can also check a live example on this repository.
    </a>
  </div>

  <div class="card">
    <% if @project.api_auth_digest.blank? %>
      <h3>Create API Token</h3>
      <div class="card bg-warning text-warning-content mb-3">
        This project doesn't have an API token yet.
        <br />
        Create one to start sending reports...
      </div>
    <% else %>
      <h3>Reset API Token</h3>
      <div class="card bg-warning text-warning-content mb-3">
        Your previous API token will no longer work if you reset this!
      </div>
    <% end %>

    <%= form_with model: @project, class: "flex flex-col items-start gap-4" do |form| %>
      <%= form.hidden_field :reset_api_auth, value: true %>
      <% if @project.api_auth_digest.blank? %>
        <%= form.submit "Create 🚀", class: "button" %>
      <% else %>
        <%= form.submit "Reset!", class: "button", data: { "turbo-confirm": "Are you sure? Your previous token will stop working!"} %>
      <% end %>

    <% end %>
  </div>
</div>