config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  root "home#index"

  get "up" => "rails/health#show", as: :rails_health_check

  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  resources :organizations, only: %i[index create show]
  resources :organization_users, only: %i[create]
  resources :projects, only: %i[create show update]
  resources :reports, only: %i[] do
    member do
      get :bundled_html, action: :bundled_html
      get "bundled_html/*path", action: :bundled_html
    end
  end


  namespace :api do
    resources :reports, only: %i[] do
      collection do
        post :simplecov
      end
    end
  end
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :organization_users
  has_many :users, through: :organization_users

  has_many :projects
  has_many :reports

  validates :handle,
            presence: true,
            format: {
              with: /\A[a-z0-9\-]+\z/,
              message: "accepts only lowercase letters, numbers, and hyphens. Eg: 'my-company-name'"
            },
            uniqueness: true
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  def index
    @organizations = organizations.all
  end

  def create
    @organization = Organization.new(create_params)

    if @organization.save
      OrganizationUser.create(organization: @organization, user: current_user)

      flash[:success] = "Organization '#{@organization.handle}' created successfully!"
      redirect_to organizations_path
    else
      flash[:danger] = @organization.errors.full_messages.to_sentence
      redirect_back(fallback_location: organizations_path)
    end
  end

  def show
    @organization = organizations.find(params[:id])
    @projects = @organization.projects
    @users = @organization.users
  end

  private

  def create_params
    params
      .require(:organization)
      .permit(:handle)
      .tap do |partial_params|
        partial_params[:handle] = partial_params[:handle]&.parameterize
      end
  end

  def organizations
    current_user.organizations
  end
end

app/views/organizations/index.html.erb
<h1>Organizations</h1>

<div class="flex justify-between">
  <ul class="list-disc">
    <% if @organizations.blank? %>
      <li>No organizations yet...</li>
    <% end %>

    <% @organizations.each do |organization| %>
      <li><a href="<%= organization_path(organization) %>" class="link"><%= organization.handle %></a></li>
    <% end %>
  </ul>

  <div class="card inline-block">
    <h3>Create new organization</h3>

    <%= form_with model: Organization.new, class: "flex flex-col items-start gap-2" do |form| %>
      <div>
        <%= form.label :handle %>
        <%= form.text_field :handle, placeholder: "my-company-name" %>
        <div class="text-xs mt-1">Only lowercase letters, numbers, and hyphens. Eg: 'my-company-name'</div>
      </div>

      <%= form.submit "Create", class: "button" %>
    <% end %>
  </div>
</div>

app/views/organizations/show.html.erb
<h6><%= link_to "< Organizations", organizations_path, class: "link" %></h6>
<h5>Organization</h5>
<h1><%= @organization.handle %></h1>

<div class="flex justify-between">
  <ul class="list-disc">
    <h4>Projects</h4>

    <% if @projects.blank? %>
      <li>No projects yet...</li>
    <% end %>

    <% @projects.each do |project| %>
      <li><a href="<%= project_path(project) %>" class="link"><%= project.handle %></a></li>
    <% end %>
  </ul>

  <div class="card inline-block">
    <h3>Create new project</h3>

    <%= form_with model: Project.new, class: "flex flex-col items-start gap-4" do |form| %>
      <%= form.hidden_field :organization_id, value: @organization.id %>

      <div>
        <%= form.label :handle %>
        <%= form.text_field :handle, placeholder: "my-github-repo" %>
        <div class="text-xs mt-1">Only lowercase letters, numbers, and hyphens. Eg: 'my-github-repo'</div>
      </div>

      <%= form.submit "Create", class: "button" %>
    <% end %>
  </div>
</div>

<hr class="my-8" />

<div class="flex justify-between">
  <ul class="list-disc">
    <h4>Users</h4>

    <% @users.each do |user| %>
      <li><%= user.handle %></li>
    <% end %>
  </ul>

  <div class="card inline-block">
    <h3>Invite user</h3>

    <%= form_with model: OrganizationUser.new, class: "flex flex-col items-start gap-4" do |form| %>
      <%= form.hidden_field :organization_id, value: @organization.id %>

      <div>
        <%= form.label :user_handle %>
        <%= form.text_field :user_handle, placeholder: "my-friend-handle" %>
        <div class="text-xs mt-1">The user must have already been signed up with their Github.</div>
        <div class="text-xs"><%= link_to "Send them this link if they haven't signed up yet", root_path, class: "link" %></div>
      </div>

      <%= form.submit "Invite", class: "button" %>
    <% end %>
  </div>
</div>