config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks" }

  root "home#index"

  get "up" => "rails/health#show", as: :rails_health_check

  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  resources :organizations, only: %i[index create show]
  resources :organization_users, only: %i[create]
  resources :projects, only: %i[create show update]
  resources :reports, only: %i[] do
    member do
      get :bundled_html, action: :bundled_html
      get "bundled_html/*path", action: :bundled_html
    end
  end


  namespace :api do
    resources :reports, only: %i[] do
      collection do
        post :simplecov
      end
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Flaky" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-neutral text-neutral-content">
    <nav class="absolute right-0 top-0">
      <ul class="flex gap-6 p-4">
        <% if user_signed_in? %>
          <li><%= link_to "Your organizations", organizations_path, class: "link" %></li>
          <li><%= button_to "Sign out", destroy_user_session_path, data: { turbo: false }, method: :delete %></li>
        <% else %>
          <li><%= button_to "Sign in with Github", user_github_omniauth_authorize_path, data: { turbo: false } %></li>
        <% end %>
      </ul>
    </nav>

    <main class="container mx-auto p-5">
      <div>
        <% flash.each do |key, message| -%>
          <%= content_tag :div, message, class: class_names("card mb-4", flash_class_names(key)) %>
        <% end -%>
      </div>

      <%= yield %>
    </main>
  </body>
</html>